### ISSUE TITLE
Tool-tip does not open documentation or source

### ISSUE THREAD

**Issue by freeman42x** [Tehnix/ide-haskell-hie#21] opened 2018-04-01 00:34 UTC
Tool-tip does not open documentation or source on click, all that happens is that the link becomes underlined after the click.

With LSP logging enabled there are no new messages caused by the click.

**Comment by Tehnix** [comment] 2018-04-01 22:40
Currently no handlers haven't been implemented. The status of this is tracked here https://github.com/Tehnix/ide-haskell-hie/issues/2, so I'll close this as a duplicate of that.

**Closed as completed by Tehnix** 2018-04-01 22:40 UTC
Labels: duplicate
