### ISSUE TITLE
HIE and Atom

### ISSUE THREAD

**Issue by Bendodroid** [Tehnix/ide-haskell-hie#33] opened 2018-11-25 17:16 UTC
I installed HIE with stack and the atom plugin ide-haskell-hie and the only change so far is that HIE initializes forever (little circle in the status bar) and I no longer have autocompletion.

How is this supposed to work?

**Comment by colbyn** [comment] 2019-01-19 23:58
Hey @Bendodroid  if it helps.  I installed HIE via the `make build-all` command. After installing `ide-haskell-hie` I clicked on the ‘Use the hie-wrapper’ button and restarted Atom, and thereafter everything (including autocomplete) seems to be working…

**Comment by Tehnix** [comment] 2019-03-18 10:49
I'll close this as a duplicate of https://github.com/Tehnix/ide-haskell-hie/issues/34 (keeping that one because it had a more descriptive title).

Usually the core issue is that the HIE version does not match your project.

**Closed as completed by Tehnix** 2019-03-18 10:49 UTC
Labels: duplicate
